services:
  xks-proxy:
    image: xks-proxy:latest
    volumes:
      - "./config/settings.toml:/var/local/xks-proxy/.secret/settings.toml"
    ports:
      - "80:80"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --loglevel debug --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
