# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

[server]
ip = "0.0.0.0"
port = 80
region = "ap-south-1"
service = "kms-xks-proxy"

[server.tcp_keepalive]
tcp_keepalive_secs = 60
tcp_keepalive_retries = 5
tcp_keepalive_interval_secs = 1

[tracing]
is_stdout_writer_enabled = true
is_file_writer_enabled = false
level = "DEBUG"

[security]
is_sigv4_auth_enabled = true
is_tls_enabled = false
is_mtls_enabled = false

[[external_key_stores]]
uri_path_prefix = "/aws-redteam-kit"
sigv4_access_key_id = "AKIAHPRO52CGOA4VJPU4"
# Access key ID must have between 20 and 30 characters. Valid characters are uppercase A-Z and 2-7
sigv4_secret_access_key = "yTBJ7hqzT7TTtqCHGqFjJQDTJaZolkCz5i5h5TUSwHNUK1glZ6rMpQ=="
# Secret access key must have between 43 and 64 characters. Valid characters are a-z, A-Z, 0-9, /, +, and =
xks_key_id_set = ["foo"]
# This should match the key name in dockerfile

[pkcs11]
session_pool_max_size = 30
session_pool_timeout_milli = 0
session_eager_close = false
user_pin = "1234"
# PKCS11_HSM_MODULE = "/usr/local/lib/pkcs11-logger-x64.so"
PKCS11_HSM_MODULE = "/usr/lib/softhsm/libsofthsm2.so"
context_read_timeout_milli = 10

[pkcs11_logger]
PKCS11_LOGGER_LIBRARY_PATH = ""
PKCS11_LOGGER_LOG_FILE_PATH = ""
PKCS11_LOGGER_FLAGS = "0"

[limits]
max_plaintext_in_base64 = 8192
max_aad_in_base64 = 16384

[hsm_capabilities]
can_generate_iv = false
is_zero_iv_required = false
